# Generated by Django 3.1.7 on 2021-04-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210330_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='desc',
            field=models.CharField(blank=True, max_length=144),
        ),
    ]
