# Generated by Django 3.1.7 on 2021-03-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
